// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//import 'package:firebase_core/firebase_core.dart'
//show FirebaseOptions;
//import 'package:flutter/foundation.dart'
    //show defaultTargetPlatform, kIsWeb, TargetPlatform;

 //Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
//class DefaultFirebaseOptions {
  //static FirebaseOptions get currentPlatform {
    //if (kIsWeb) {
      //return web;
    //}
    //switch (defaultTargetPlatform) {
      //case TargetPlatform.android:
        //return android;
      //case TargetPlatform.iOS:
        //return ios;
      //case TargetPlatform.macOS:
        //return macos;
      //case TargetPlatform.windows:
        //return windows;
      //case TargetPlatform.linux:
        //throw UnsupportedError(
          //'DefaultFirebaseOptions have not been configured for linux - '
          //'you can reconfigure this by running the FlutterFire CLI again.',
        //);
      //default:
        //throw UnsupportedError(
          //'DefaultFirebaseOptions are not supported for this platform.',
        //);
    //}
  //}

  //static const FirebaseOptions web = FirebaseOptions(
    //apiKey: 'AIzaSyCWtbpRKBKCCGqQKNswZAT-DXw9zXLKuz8',
    //appId: '1:740791302835:web:9c4568683d2c830d064ec6',
    //messagingSenderId: '740791302835',
    //projectId: 'agriyouth-6dba1',
    //authDomain: 'agriyouth-6dba1.firebaseapp.com',
    //storageBucket: 'agriyouth-6dba1.firebasestorage.app',
    //measurementId: 'G-2R4NCNW21E',
  //);

  //static const FirebaseOptions android = FirebaseOptions(
    //apiKey: 'AIzaSyAF5jP2nBPSYbQsgBLdeK78ErXEvq-o3Gk',
    //appId: '1:740791302835:android:55aaa1fd5e3fcf73064ec6',
    //messagingSenderId: '740791302835',
    //projectId: 'agriyouth-6dba1',
    //storageBucket: 'agriyouth-6dba1.firebasestorage.app',
  //);

  //static const FirebaseOptions ios = FirebaseOptions(
    //apiKey: 'AIzaSyBnrAO4cNzBC9EmYuLgpeZ3KkUK5vo4mnc',
    //appId: '1:740791302835:ios:287a74a8bc703c64064ec6',
    //messagingSenderId: '740791302835',
    //projectId: 'agriyouth-6dba1',
    //storageBucket: 'agriyouth-6dba1.firebasestorage.app',
    //iosBundleId: 'co.za.flutterapp',
  //);

  //static const FirebaseOptions macos = FirebaseOptions(
    //apiKey: 'AIzaSyBnrAO4cNzBC9EmYuLgpeZ3KkUK5vo4mnc',
    //appId: '1:740791302835:ios:287a74a8bc703c64064ec6',
    //messagingSenderId: '740791302835',
    //projectId: 'agriyouth-6dba1',
    //storageBucket: 'agriyouth-6dba1.firebasestorage.app',
    //iosBundleId: 'co.za.flutterapp',
  //);

  //static const FirebaseOptions windows = FirebaseOptions(
    //apiKey: 'AIzaSyCWtbpRKBKCCGqQKNswZAT-DXw9zXLKuz8',
    //appId: '1:740791302835:web:f4f3ee279b4abced064ec6',
    //messagingSenderId: '740791302835',
    //projectId: 'agriyouth-6dba1',
    //authDomain: 'agriyouth-6dba1.firebaseapp.com',
    //storageBucket: 'agriyouth-6dba1.firebasestorage.app',
    //measurementId: 'G-VNBNZVJZ2D',
  //);
//}
